name: build-check

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'
      - run: make project-build


  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

        - name: Test & publish code coverage
          uses: paambaati/codeclimate-action@v3.0.0
          env:
            CC_TEST_REPORTER_ID: 0934b5229b53b57aba63ef708704fe47bc2e55069b23745ae8700386ed6926b1
            JACOCO_SOURCE_PATH: "${{github.workspace}}/src/main/java"
          with:
            coverageCommand: make test
            coverageLocations: ${{github.workspace}}//build/jacocoHtml/index.html:jacoco